package edu.tecnilogica.entity;
// Generated 27-jun-2017 12:19:37 by Hibernate Tools 5.1.4.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.TableGenerator;

/**
 * Registrotable generated by hbm2java
 */
@Entity
@Table(name = "REGISTROTABLE", schema = "HR")
@TableGenerator(
		name = "course",
		table="IDTABLA",
		pkColumnName="sequence_name",
		valueColumnName="nextval",
		allocationSize=30)
public class Registrotable implements java.io.Serializable {

	private BigDecimal id;

	public Registrotable() {
	}

	public Registrotable(BigDecimal id) {
		this.id = id;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.TABLE, generator="course")
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

}
