package edu.tecnilogica.entity;
// Generated 27-jun-2017 12:19:37 by Hibernate Tools 5.1.4.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RegistroSeq generated by hbm2java
 */
@Entity
@Table(name = "REGISTRO_SEQ", schema = "HR")
public class RegistroSeq implements java.io.Serializable {

	private BigDecimal id;

	public RegistroSeq() {
	}

	public RegistroSeq(BigDecimal id) {
		this.id = id;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

}
