package edu.tecnilogica.entity;
// Generated 27-jun-2017 12:19:37 by Hibernate Tools 5.1.4.Final

import java.util.UUID;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Registro generated by hbm2java
 */
@Entity
@Table(name = "REGISTRO", schema = "HR")
public class Registro implements java.io.Serializable {

	private UUID id;

	public Registro() {
	}

	public Registro(UUID id) {
		this.id = id;
	}

	@Id
	@GeneratedValue
	@Column(name = "ID", unique = true, nullable = false, length = 36)
	public UUID getId() {
		return this.id;
	}

	public void setId(UUID id) {
		this.id = id;
	}

}
